Repository iterative/setup-cml, pull requests merged in 2021-09, with the labels that each got.

#37 Run check.yml on pull request instead of on push
  .github/workflows/check.yml
Labels: testing

#36 Optional sudo usage
  README.md
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/github-action.js
  src/utils.js
Labels: enhancement

#41 Pin manually installed packages to major versions
  dist/index.js
  src/utils.js
Labels: bug

#43 npm update
  package-lock.json
  package.json
Labels: bug, dependencies

#46 pin node engines
  package.json
Labels: bug, dependencies
